sonar.projectKey=devops-ecommerce
sonar.projectName=DevOps E-Commerce Platform
sonar.projectVersion=1.0

# Frontend
sonar.sources=frontend/src
sonar.exclusions=**/node_modules/**,**/build/**

# Backend
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality Gate
sonar.qualitygate.wait=true

# Language
sonar.language=js
sonar.sourceEncoding=UTF-8